### ISSUE TITLE
第五次印刷勘误

### ISSUE THREAD

**Issue by NooobQ** [xiexiexx/Translations#2]
第26页：正确性证明-习题1-7最后一行的括号有误，应该在加号前闭括号，而不是在最后
 return(multiply($ cy,\lfloor z/c \rfloor)+y \cdot (z\,\bmod\,c $))
[https://www.algorist.com/algowiki_v2/index.php/Introduction-TADM2E](https://www.algorist.com/algowiki_v2/index.php/Introduction-TADM2E)

**Comment by xiexiexx** [comment]
才看到。
